<?php
   ob_start();  //FOR STOP REPEATE THE ACTION WHEN WE REFRASH

   include('Includes/Header.php');
?>
   
   <!-- ##### Breadcumb Area Start ##### -->
    <div class="breadcumb_area bg-img" style="background-image: url(Admin/images/icon/Shop_BG.jpg);">
        <div class="container h-100">
            <div class="row h-100 align-items-center">
                <div class="col-12">
                    <div class="page-title text-center">
                        <h2>Privacy Policy</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Breadcumb Area End ##### -->

    <!-- ##### Shop Grid Area Start ##### -->
<div style="margin:20px;">
    <h2>1. Data Protection Statement</h2>
    <P style="margin:20px;">We thank you for your interest in our website's products and services. 
    Protecting your personal data is very important for us. The following text informs you in detail 
    about how we handle and protect your data.</p>
    <h6>1.1. Storage of Access Data on Server Log Files</h6>
    <P style="margin:20px;">You can visit our websites without being required to enter any personal data. 
    We only save access data in so-called server log files, for example the name of a requested file, the 
    date and time of retrieval, the data volume transferred and the requesting provider. These data are 
    exclusively used to ensure a trouble-free operation of the website and they are evaluated to improve 
    our services. They do not allow any conclusions to be made with regard to your person.</p>
    <h6>1.2. Data Collection and Data Use for Contract Processing and when Opening Customer Accounts</h6>
    <P style="margin:20px;">We collect personal data only when you provide your data voluntarily in the 
    context of ordering products, contacting us (e.g. using the contact form or by e-mail) or opening a 
    customer account. From the relevant input form you can see which data are collected. We use the data 
    provided by you to process the contracts and your inquiries. After final processing of the contract or 
    deletion of your customer account your data are blocked for further use and deleted upon expiry of the 
    retention periods pursuant to fiscal and commercial law unless you have given your express consent to a 
    further use of the data or if we reserve the right to legally admissible data usage going beyond this 
    of which we inform you below. Deletion of your customer account is possible anytime. To do so, you can 
    either send us a message using the e-mail address specified below or use the relevant function available 
    in the customer account.</p>
    <h6>1.3. Data Transfer for Contract Performance</h6>
    <P style="margin:20px;">To perform the contract, we forward your data to the shipping company which was 
    instructed to deliver the goods where necessary to deliver the ordered goods.</p>
    <h6>1.4. Use of Data when Registering for E-Mail Newsletters</h6>
    <P style="margin:20px;">If you register for our newsletter, we will use the data required for this 
    process or the data you have given to us separately in order to regularly send you our e-mail newsletter. 
    You can unsubscribe from the newsletter at any time. To do so, you can either send us a message by e-mail, 
    Or you can manage your subscriptions from the account settings under your profile information.</p>
    <h6>1.5. Use of Cookies</h6>
    <P style="margin:20px;">We use cookies on various pages in order to make our website more attractive 
    to visitors and to enable the use of certain functions. Cookies are small text files that are saved on 
    your computer. Some of the cookies we use are automatically deleted after a browser session, i.e. 
    after closing your browser (so-called session cookies). Other cookies remain stored on your computer 
    and allow us to re-identify your browser when you log on again (persistent cookies). You can set the 
    browser such that the computer informs you of relevant cookies and you can decide in each individual 
    case if you accept cookies or accept them only in certain cases or refuse them in general. 
    If you do not accept cookies, some features of the website may not function properly or fully.</p>
    <h6>1.6. Use of Google Analytics for Web Analysis</h6>
    <P style="margin:20px;">This website uses Google Analytics, a web analytics service provided by Google, 
    Inc. (www.google.de). Google Analytics uses "cookies" which are text files placed on your computer to 
    help the website analyze how users use the site. The information generated by the cookies about your use 
    of the website (including your IP address) will usually be transmitted to and stored by Google on servers 
    in the United States. In case IP anonymization is activated on this website, Google uses your IP address 
    in a truncated form within European Union member states or in other signatories of the Agreement on the 
    European Economic Area. Only in exceptional cases, the full IP address is transmitted to servers of 
    Google in the US and truncated there. IP anonymization is activated on this website. On behalf of the 
    operator of this website, Google will use this information for the purpose of evaluating your use of 
    the website, compiling reports on website activity for website operators and providing other services 
    relating to website activity and internet usage. Google will not associate your IP address transmitted 
    by your browser with any other data held by Google. You may refuse the use of cookies by selecting the 
    appropriate settings on your browser. Please note however that if you do this you may not be able to 
    fully benefit from all features of this website.Furthermore you can prevent the collection of data 
    generated by the cookie and related to your use of the website (incl. your IP address) by Google and 
    the processing of these data by Google by downloading and installing a specific browser plugin available 
    by using the following link:http://tools.google.com/dlpage/gaoptout?hl=enAs an alternative to this 
    browser plugin, you may click on this link to prevent future collection of data by Google Analytics on 
    this website. An opt-out cookie is placed on your terminal. If you delete your cookies, you must again 
    click on the link.</p>
    <h6>1.7. Right to Information and Contact Options</h6>
    <P style="margin:20px;">You are entitled to free information about your stored personal data at any 
    time as well as the right to correction, refusal of access or deletion of your data. If you have any 
    questions about the collection, processing or use of your personal data, in case of inquiries, 
    correction, refusal of access or deletion of data as well as revocation of granted permissions or 
    objection against a certain type of usage, please contact us directly. The contact details are listed 
    in our Imprint. </p>
    <h2>2. Final Provisions</h2>
    <P style="margin:20px;">If you are an entrepreneur, you are subject to the law of the Hashimite kingdom 
     Jordan and its courts.If you are a tradesperson, a legal entity under public law or a special fund under 
     public law, the exclusive place of jurisdiction for all legal disputes arising from contractual 
     relations between you and us is our place of business.</p>
</div>
<?php
    include('Includes/Footer.php');
?>